### ISSUE TITLE
Rendering with different objects in batch

### ISSUE THREAD

**Issue by raoshashank** [NVlabs/diff-dope#3]
Hi!
I was wondering how I would go about using the rendering functions (render_texture_batch mostly) when I would like to pass a batch of different objects (meshes) as input. 
Pytorch3d is able to achieve this I'm not sure how, but they might be doing some padding, however since nvdiffrast is more barebones, I'm not sure how it would work here..
Thank you!

**Comment by TontonTremblay** [comment]
I dont think so. 

You would need to pass a triangle list with a batch in this function 

<img width="867" alt="image" src="https://github.com/NVlabs/diff-dope/assets/5629088/9703429a-f4a9-4969-a43d-69bb371ad4f6">

**Comment by raoshashank** [comment]
Yes, Looks like nvdiffrast's [range-mode](https://github.com/NVlabs/nvdiffrast/issues/22) is the answer. Thanks!

**Comment by raoshashank** [comment]
I have tried the range mode and it actually only appears to be rasterizing and interpolating the first minibatch index correctly, even though I'm passing the correct ranges tensor to the rasterize function (containing the start index and the counts of the triangles per batch). I saw some interest in this in a different issue so I'm reopening this, however I'm not sure if this is a bug w.r.t nvdiffrast or the documentation is misleading

**Comment by raoshashank** [comment]
The problem is solved, please refer: https://github.com/NVlabs/nvdiffrast/issues/164

**Comment by TontonTremblay** [comment]
Are you results correct? Please share them, if this is something useful, I would love to include this into the main repo --- though I do not want to steal your research you might be doing.

**Comment by TontonTremblay** [comment]
I just looked at your other post. Yeah it looked like you needed to offset the positions in the triangle ids. :D

**Comment by raoshashank** [comment]
yup, I've provided the code that was modified in the above comment, and the results after the fix in the nvdiffrast issue as well
