### ISSUE TITLE
Question about the constraints on the initial pose error

### ISSUE THREAD

**Issue by raoshashank** [NVlabs/diff-dope#5]
I have been running some experiments using this codebase on my own work and I've seen the Diff-Dope video on the website as well. I wanted to ask, is it a requirement that the mask of the object at the initial pose and the mask of the object at the target pose have some intersection (otherwise the gradients w.r.t the losses would be zero), and whether this is a general assumption for image-based pose refinement, i.e, the initial pose is already somewhere in close vicinity of the target pose.

**Comment by TontonTremblay** [comment]
yeah they would need to overlap. The initial design is for pose refinement, so the initial pose should already be pretty good. That being said, you could design a search algorithm that would relax this requirement.

**Comment by raoshashank** [comment]
Makes Sense since this is intended for fine refinement of pose. Thanks!
